import type { Metadata, Viewport } from "next";
import { Geist, Quicksand } from "next/font/google";
import "./globals.css";
import { BRAND_THEME_COLOR, BRAND_SURFACE_COLOR_DARK } from "@/lib/brand";
import { appleStartupImages } from "@/lib/apple-splash";
import { ServiceWorkerRegister } from "./sw-register";
import {
  ThemeProvider,
  THEME_NO_FLASH_SCRIPT,
} from "@/components/theme/theme-provider";
import { MotionProvider } from "@/components/motion/motion-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Rounded, friendly display face — echoes the Youth Nexus wordmark.
const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Cetele — group dhikr tracker",
  description:
    "Track your daily dhikr together. A shared tally that makes remembrance a habit.",
  applicationName: "Cetele",
  // Static assets under /public referenced directly — NOT the app/icon file
  // convention, whose ICO/PNG image processing rejected the generated marks.
  // logo.svg is the crisp modern favicon; the 192 PNG is the raster fallback.
  icons: {
    icon: [
      { url: "/logo.svg", type: "image/svg+xml" },
      { url: "/icons/icon-192.png", type: "image/png", sizes: "192x192" },
    ],
    apple: "/apple-icon.png",
  },
  appleWebApp: {
    // `capable` now emits the modern `mobile-web-app-capable` (Apple deprecated
    // the `apple-`prefixed one, and Next strips it from every channel). That
    // enables standalone + the startup images below on iOS 16.4+ — the whole
    // practical iOS base; don't try to re-add the old meta, it won't render.
    capable: true,
    statusBarStyle: "default",
    title: "Cetele",
    // iOS ignores the manifest background_color and shows BLACK on cold start
    // without these — one launch image per device size + orientation, matched by
    // an exact media query. Generated by `node scripts/gen-splash.mjs` from the
    // same table these tags read (lib/apple-splash.js), so they can't drift.
    startupImage: appleStartupImages,
  },
};

export const viewport: Viewport = {
  // Brand sage tints the browser chrome in light; in dark it takes the warm
  // surface so the status-bar area blends instead of glaring. (Driven by the
  // system scheme — the only signal a static meta tag has.)
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: BRAND_THEME_COLOR },
    { media: "(prefers-color-scheme: dark)", color: BRAND_SURFACE_COLOR_DARK },
  ],
  width: "device-width",
  initialScale: 1,
  // NO `maximumScale` / `userScalable: false`. Capping the scale blocks
  // pinch-zoom, which is a WCAG 1.4.4 (Resize Text) failure — and this is an
  // app people read Arabic transliteration in. The usual reason to cap it is
  // iOS Safari auto-zooming on focused inputs; that is fixed at the source
  // instead, by giving `Input` a 16px type size on phones (see input.tsx).
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${quicksand.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <script dangerouslySetInnerHTML={{ __html: THEME_NO_FLASH_SCRIPT }} />
        <ThemeProvider>
          <MotionProvider>
            {children}
            <ServiceWorkerRegister />
          </MotionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
